#!/usr/bin/env ruby

require 'rubygems'
require 'rb-fsevent'
require 'optparse'

skippable_directories = [ '.idea', '.git', '.svn', '.cvs' ]

# set default options
options = {
	:user => nil,
	:host => nil,
	:port => nil,
	:dir => nil,
	:exclude => nil,
	:include => nil,
	:follow => nil,
	:remove => nil,
	:symlink => '-L'
}

optparse = OptionParser.new do |opts|
	# Set a banner, displayed at the top
	# of the help screen.
	opts.banner = "Usage: #{$0} [options] file1 file2 ..."

	# Define the options, and what they do
	opts.on('-u', '--user USER', 'User name for remote host') do |user|
		options[:user] = user
	end

	opts.on('-H', '--host HOST', 'Remote host to connect') do |host|
		options[:host] = host
	end

	opts.on('-p', '--port PORT', 'Remote port to connect') do |port|
		options[:port] = port
	end

	opts.on('-d', '--directory DIR', 'Base directory on remote host') do |dir|
		options[:dir] = dir
	end

	opts.on('-e', '--exclude-paths EXCLUDE', 'File paths to exclude from the sync, separated by spaces') do |exclude|
		options[:exclude] = exclude
	end

	opts.on('-i', '--include-paths INCLUDE', 'File paths to include in the sync, separated by spaces') do |include|
		options[:include] = include
	end

	opts.on('-f', '--follow-symlinks', 'Listen to symlinked directories') do
		options[:follow] = true
	end

	opts.on('-r', '--delete', 'Remove remote files that have been deleted locally') do |remove|
		options[:remove] = '--delete'
	end

	opts.on('-s', '--preserve-symlinks', 'Preserve symlinks') do
		options[:symlink] = '-l'
	end

	# This displays the help screen, all programs are
	# assumed to have this option.
	opts.on('-h', '--help', 'Display this screen') do
		puts opts
		exit
	end
end

optparse.parse!

if !options[:user] then
	puts "Please provide a user name with option -u USER or --user USER. Run #{$0} --help for more info."
	exit
end

if !options[:host] then
	puts "Please provide a host name with option -H HOST or --host USER. Run #{$0} --help for more info."
	exit
end

if !options[:dir] then
	puts "Please provide a remote directory with option -d DIR or --dir DIR. Run #{$0} --help for more info."
	exit
end

$exclude = ""
if options[:exclude] then
	options[:exclude].split(/ /).each do |excludePath|
		$exclude += "--exclude #{excludePath} "
	end
end

$include = ""
if options[:include] then
	options[:include].split(/ /).each do |includePath|
		$include += "--include #{includePath}"
	end
end

$d=File.basename Dir.pwd
$locations = [$d];

if options[:follow] then
	Dir.glob( File.join('.', '**', '*') ) do |filename|
	    if (File.symlink?(filename)) then
			$locations.push(File.readlink(filename))
	    end
	end
end

if options[:port] then
	options[:ssh] = "ssh -p#{options[:port]}"	
else 
	options[:ssh] = "ssh"	
end

fsevent = FSEvent.new
Dir.chdir '..'

$sync = "rsync #{options[:symlink]} -C #{options[:remove]} -rt --rsh='#{options[:ssh]}' #{$include} #{$exclude} '#{$d}' '#{options[:user]}@#{options[:host]}:#{options[:dir]}'" 

system "/usr/local/bin/growlnotify -a 'Network Utility' -m 'Syncer2.0 started'"
system $sync
system "/usr/local/bin/growlnotify -a 'Network Utility' -m 'Initial sync complete'"

fsevent.watch $d do |directories|
	system $sync

	if !directories.inspect.scan(Regexp.new(skippable_directories.join('|')))
		system "/usr/local/bin/growlnotify -a 'Network Utility' -m 'Synced changes inside: #{directories.inspect}'"
	end
end

fsevent.run
